FROM nginx:alpine
RUN apk --no-cache add gettext
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY ./src/main/resources/static/*.html /usr/share/nginx/html/
CMD ["/bin/sh", "-c", "for file in /usr/share/nginx/html/*.html; do envsubst '${SERVER_ADDRESS}' < $file > temp.html && mv temp.html $file; done && nginx -g 'daemon off;'"]
EXPOSE 80
